### ISSUE TITLE
LUA Error: [string "DeIce_PITOT_off()"]:1: attempt to call global 'DeIce_PITOT_off' (a nil value)

### ISSUE THREAD

**Issue by BlueMooney** [joeherwig/msfs-fsuipc-lua-scripts#1]
Joe,
---------------------------------------------------------------------------------------------------------------------------------
EDIT:  Please disregard this post.   I figured out my numerous problems in making TripleUse work on my system.  It was all my misunderstanding and lack of knowledge about FSUIPC, LUA and LINDA and not being able to follow your examples.   I posted details about my erroneous method on  the FSUIPC forum.    Again thanks for sharing.
--------------------------------------------------------------------------------------------------------------------------------

Thanks for creating TripleUse.com.   I use "HomeFries" T.A.R.G.E.T. profiles in DCS World and have grown extremely fond of having short, double and long presses on the buttons of my HOTAS controllers and would love to be able to do this in P3D and MSFS.

I am trying to get your TripleUse working on my system, but apparently I am doing something wrong.   I am a raw novice with LUA code, but thought I understood how to set things up by following your examples.   When I try executing TripleUse, FSUIPC (or maybe LUA?) gives me the following errors:

321469 *** LUA Error: [string "DeIce_PITOT_off()"]:1: attempt to call global 'DeIce_PITOT_off' (a nil value)
326437 *** LUA Error: D:\Programs\FSUIPC7\TripleUse.lua:45: attempt to index field '?' (a nil value)

Attached is my version of your TripleUse.lua file, my FSUIPC.INI and the FSUIPC.LOG
[TripleUse.lua.txt](https://github.com/joeherwig/msfs-fsuipc-lua-scripts/files/5861586/TripleUse.lua.txt)
[FSUIPC7.ini.txt](https://github.com/joeherwig/msfs-fsuipc-lua-scripts/files/5861587/FSUIPC7.ini.txt)
[FSUIPC7.log.txt](https://github.com/joeherwig/msfs-fsuipc-lua-scripts/files/5861594/FSUIPC7.log.txt)

Only change I have made to your TripleUse file is including your btnFunc array within the file rather than loading it with the dofile([[.\TripleUseAssignments.lua]]) statement.

Any help would be greatly appreciate.

Alan

**Comment by joeherwig** [comment]
Hi Alan,

Thanks for your recommendation. 
You're totally right. Fixed now. Should work as you expect.
Thanks for your great analysis and the opened issue.

Have fun with it...

Joe

**Comment by joeherwig** [comment]
Hi Alan,

The reason was, that the `DeIce_PITOT_off()` is located in the lib-msfs.lua which was not made available.
Fixed by https://github.com/joeherwig/msfs-fsuipc-lua-scripts/blob/main/TripleUse.lua#L7.
